services:

  namenode:
    build:
      context: .
      dockerfile: hdfs_namenode/Dockerfile
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hdfs-net
    volumes:
      - namenode_data:/hdfs/namenode

  datanode1:
    build:
      context: .
      dockerfile: hdfs_datanode/Dockerfile
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode
    networks:
      - hdfs-net
    volumes:
      - datanode1_data:/hdfs/datanode

#  datanode2:
#    build:
#      context: .
#      dockerfile: hdfs_datanode/Dockerfile
#    container_name: datanode2
#    hostname: datanode2
#    depends_on:
#      - namenode
#    networks:
#      - hdfs-net
#    volumes:
#     - datanode2_data:/hdfs/datanode

networks:
  hdfs-net:

volumes:
  namenode_data:
  datanode1_data:
  #datanode2_data: